import './jquery'
import 'admin-lte/plugins/jQueryUI/jquery-ui'
import 'font-awesome/css/font-awesome.css'
import 'ionicons/dist/css/ionicons.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'admin-lte/dist/css/AdminLTE.css'
import 'admin-lte/dist/css/skins/_all-skins.css'
import 'admin-lte/plugins/iCheck/flat/blue.css'

import './app.css'
